pipeline:
  name: abc
  identifier: abc
  projectIdentifier: abc
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cs
        identifier: cs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "eyh"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
