pipeline:
  nasadfsadme: cnsssssfdasfs-cd-gold-appp-preprod
  identifier: cns_cd_gold_appp_preprod
  projectIdentifier: OPA_TEST
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: ss
        identifier: ss
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
