pipeline:
  name: Remote_Pipeline_Github
  identifier: Remote_Pipeline_Github
  projectIdentifier: OPA_TEST
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+secrets.getValue("<+pipeline.variables.test_user_name>")> | rev
                          echo <+secrets.getValue("<+pipeline.variables.test_user_name>")> | rev
                          exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: sec
      type: String
      description: ""
      required: true
      value: <+input>
