pipeline:
  name: Remote_Pipeline_Github
  identifier: Remote_Pipeline_Github
  projectIdentifier: OPA_TEST
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: ss
        identifier: ss
        description: ""
        type: Pipeline
        spec:
          org: Ng_Pipelines_K8s_Organisations
          pipeline: Test_Pipeline_1
          project: OPA_TEST
