pipeline:
  name: testing
  identifier: testing
  projectIdentifier: gittest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testsssgut
        identifier: testsssgut
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "git testugbudj"
                          exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
