pipeline:
  name: testing rem
  identifier: testing_rem
  projectIdentifier: Testim
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: fdsa
        identifier: fdsa
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hihihihihhi 2nd branch"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
