name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        grunt

    - name: Trigger Harness
      run: |
          curl -X POST -H 'content-type: application/json' --url 'https://app.harness.io/gateway/pipeline/api/webhook/custom/nb0WWZeNQcSLUkM3hYKOXg/v3?accountIdentifier=jGS2jB1ZSZG2RiLHVR0gew&orgIdentifier=default&projectIdentifier=Sameed_Test&pipelineIdentifier=approval_test_brother&triggerIdentifier=ffff' -d '{"sample_key": "sample_value"}'
